version: '3.1'
services:
  mysql:
    image: mysql:8.0
    working_dir: /application
    container_name: test-app-mysql
    volumes:
      - .:/application
      - test-app-mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=fC13PHGmxo
      - MYSQL_DATABASE=test-app-db
      - MYSQL_USER=test-app-user
      - MYSQL_PASSWORD=123123123
    ports:
      - '7022:3306'

  nginx:
    image: nginx:alpine
    working_dir: /application
    container_name: test-app-nginx
    depends_on:
      - php-fpm
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '7020:80'

  php-fpm:
    build: phpdocker/php-fpm
    image: test-app-php-fpm:latest
    platform: linux/amd64
    container_name: test-app-php-fpm
    working_dir: /application
    environment:
      XDEBUG_MODE: "coverage"
    security_opt:
      - seccomp=unconfined
    depends_on:
      - mysql
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
      - ~/.ssh:/root/.ssh

volumes:
    test-app-mysql-volume:
